### ISSUE TITLE
ira_eq.x doesn't work.

### ISSUE THREAD

**Issue by FanMover** [mammasmias/IterativeRotationsAssignments#1]
Hi , @mgoonde . 

I am a student working on a project of Off-lattice Kinetic Monte Carlo. I found your paper and source code with excitement. As you mentioned in the paper(_IRA: A shape matching approach for recognition and comparison of generic atomic patterns_), in self-Learning KMC, atomic assignment is unknown amd number of atoms unset.  Traditional optimal method like SVD and assignment method like Hungarian algorithm cannot work on my system. So I downloaded your code and tried.

However, there was something wrong after I combined two .xyz system and executed ira_eq.x. 

First, variable _hd_fin_ not defined. To be honest, I don't know what it means. So i changed 
`hd_out = hd_fin` 
to
`hd_out = hd`
![image](https://user-images.githubusercontent.com/33125767/141792776-52663e7d-67a2-47eb-9a6c-bbc991940d59.png)

Second, the way you permute the coordinates is not recognized by my machine, it goes
![image](https://user-images.githubusercontent.com/33125767/141793048-0fe4b9c4-058a-41a5-8a9c-98758a901302.png)
, whenerver there is a permutation operation. So I changed it from 
`coords1(:,:) = coords1(:,nint(d_o(2,:)))`
to
`do i = 1, nat1 
coords1(:,i) = coords1_tmp(:,nint(d_o(2,i)))
end do 
`
So does the array _typ1/typ2/coords2_

After doing these rescue measures, I ran your example ./ira_eq.x < temp_ira. temp_ira is combined from _benchmark_test/data/lj_clusters/xyz/47.xyz_, same structure file in run_single.sh, and the randomized one. The two xyz structures didn't found scattered using ovito.  The result goes infinity.  

I don't know what is wrong and I am not that farmiliar with fortran. So I appreciate your help about it. Best wishes.

**Comment by mgoonde** [comment]
Hey @FanMover,
I would be interested in your project, since we are actually doing the exact same thing (off-lattice kmc). We will have a release of the kmc quite soon, and it will be posted also in t
he description here. I would appreciate if you could write me a short email of what you do.

Regarding the code problem:
 - You are right, the variable `hd_fin` is not defined. I have pushed a commit fixing this.
 - it's strange that your machine does not recognize this way of permutations. Which compiler do you use? I will change it to a more general solution (exactly as you wrote), later today
